/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLeadsUiuxRouteImport } from './routes/api/leads/uiux'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsUiuxRoute = ApiLeadsUiuxRouteImport.update({
  id: '/api/leads/uiux',
  path: '/api/leads/uiux',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/leads/uiux': typeof ApiLeadsUiuxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/leads/uiux': typeof ApiLeadsUiuxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instructor': typeof InstructorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/leads/uiux': typeof ApiLeadsUiuxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/instructor' | '/sitemap.xml' | '/api/leads/uiux'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/instructor' | '/sitemap.xml' | '/api/leads/uiux'
  id: '__root__' | '/' | '/instructor' | '/sitemap.xml' | '/api/leads/uiux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstructorRoute: typeof InstructorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiLeadsUiuxRoute: typeof ApiLeadsUiuxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/uiux': {
      id: '/api/leads/uiux'
      path: '/api/leads/uiux'
      fullPath: '/api/leads/uiux'
      preLoaderRoute: typeof ApiLeadsUiuxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstructorRoute: InstructorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiLeadsUiuxRoute: ApiLeadsUiuxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
